In [2]:
import numpy as np

x = np.arange(1, 11)

In [3]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
y = np.arange(10, 0, -1)
y

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [5]:
cond = np.array([True, True, True, True, False, False, False, False, False, False])

In [6]:
def true_false_array(cond, x, y):
    result = []
    for index, value in enumerate(cond):
        if value == True:
            result.append(x[index])
        else:
            result.append(y[index])
    return result

In [7]:
result = true_false_array(cond, x, y)
result

[1, 2, 3, 4, 6, 5, 4, 3, 2, 1]

In [8]:
result = np.where(cond, x, y)
result

array([1, 2, 3, 4, 6, 5, 4, 3, 2, 1])

In [9]:
rand_arr = np.random.randn(4,4)

In [10]:
rand_arr

array([[-0.05125494,  0.13872332, -1.31548938, -0.63999223],
       [ 0.7413006 , -1.03286825,  0.05101083,  0.99534595],
       [ 0.21486056,  0.31795933, -0.67592496, -0.84667117],
       [-0.87362805, -0.89598426,  1.42695978, -0.43498809]])

In [11]:
def true_false(rand_arr):
    result = []
    for value in rand_arr:
        vector_result = []
        for v in value:
            if v >= 0:
                vector_result.append(True)
            else:
                vector_result.append(False)
        result.append(vector_result)
    return result

In [12]:
result = true_false(rand_arr)
result

[[False, True, False, False],
 [True, False, True, True],
 [True, True, False, False],
 [False, False, True, False]]

In [13]:
truth_table = rand_arr < 0

In [14]:
truth_table

array([[ True, False,  True,  True],
       [False,  True, False, False],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [15]:
# x = 2로 채워진 4*4 배열
# y = -2로 채워진 4*4 배열
np.where(truth_table, 2, -2)

array([[ 2, -2,  2,  2],
       [-2,  2, -2, -2],
       [-2, -2,  2,  2],
       [ 2,  2, -2,  2]])

In [25]:
x = np.arange(1, 17).reshape(2,8)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [26]:
from numpy.linalg import qr, inv

inv_matrix = inv(x)
q, r = qr(x)


LinAlgError: Last 2 dimensions of the array must be square

In [46]:
np.sum(x)

136

In [47]:
np.sum(x)/16

8.5

In [48]:
np.mean(x)

8.5

In [49]:
np.min(x)

1

In [50]:
np.max(x)

16

In [51]:
np.median(x)

8.5

In [52]:
np.std(x)

4.6097722286464435

In [53]:
np.var(x)

21.25

In [54]:
np.std(x)**2 == np.var(x)

True