In [90]:
import numpy as np

In [91]:
menu = np.array([
    [2, 10],
    [3, 10],
    [4, 10],
    [5, 10],
    [6, 10],
])

name = np.array(["Chocolate", "Vanila", "Strawberry", "Orange", "Apple"])
feature = np.array(["Price", "Stock"])

In [92]:
menu[(name == "Chocolate") | (name== "Strawberry")]

array([[ 2, 10],
       [ 4, 10]])

In [93]:
menu[name == "Chocolate", feature == "Stock"]

array([10])

In [94]:
def menu_data(name_data, feature_data):
    return menu[name == name_data, feature == feature_data]

In [95]:
menu_data("Apple", "Stock")

array([10])

In [96]:
money = 0

def buy_icecream(menu, icecream, money):
    money += menu_data(icecream, "Price")
    menu[name==icecream, feature=="Stock"] -= 1
    return money

In [97]:
money = buy_icecream(menu, "Apple", money)
menu, money

(array([[ 2, 10],
        [ 3, 10],
        [ 4, 10],
        [ 5, 10],
        [ 6,  9]]),
 array([6]))

In [98]:
name = np.append(name, ["Banana"])

In [99]:
name

array(['Chocolate', 'Vanila', 'Strawberry', 'Orange', 'Apple', 'Banana'],
      dtype='<U10')

In [100]:
menu = np.append(menu, np.array([[7, 10]]), axis=0)

In [101]:
menu

array([[ 2, 10],
       [ 3, 10],
       [ 4, 10],
       [ 5, 10],
       [ 6,  9],
       [ 7, 10]])

In [102]:
money = buy_icecream(menu, "Banana", money)
menu, money

(array([[ 2, 10],
        [ 3, 10],
        [ 4, 10],
        [ 5, 10],
        [ 6,  9],
        [ 7,  9]]),
 array([13]))

In [103]:
truth = name != "Banana"

In [104]:
name = name[truth]
menu = menu[truth]

In [105]:
name, menu

(array(['Chocolate', 'Vanila', 'Strawberry', 'Orange', 'Apple'],
       dtype='<U10'),
 array([[ 2, 10],
        [ 3, 10],
        [ 4, 10],
        [ 5, 10],
        [ 6,  9]]))

In [120]:
stock = menu[:, feature=="Stock"]
stock

array([[10],
       [-2],
       [10],
       [10],
       [ 9]])

In [121]:
money = buy_icecream(menu, "Vanila", money)
stock > 5

array([[ True],
       [False],
       [ True],
       [ True],
       [ True]])

In [122]:
stock = np.where(stock>5, stock, 10)
stock

array([[10],
       [10],
       [10],
       [10],
       [ 9]])